# This is a basic workflow to help you get started with Actions

name: Create-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install 7zip
        run: apt install p7zip-full

      # Runs a set of commands using the runners shell
      - name: Create mod archive
        run: |
          modname="megapack_improved_$(git tag)"
          mv megapack_improved/megapack_improved_dev.xml "megapack_improved_dev/$modname.xml"
          mv megapack_improved_dev/ "$modname/"
          7z a -t7z "$modname.7z" "$modname/"

      - uses: actions/upload-artifact@v2
        with:
          path: *.7z
